device_ip = "192.168.1.100"

[output.text]
playing = "▶️ {artist} - {title} {quality_info}"
paused = "⏸️ {artist} - {title}"
stopped = "⏹️ No music"
loading = "⏳ Loading..."

[output.json]
text = "{artist} - {title}"
alt = "{state}"
tooltip = "{title}\nArtist: {artist}\nVolume: {volume}%"
class = "{state}"

[profiles.waybar]
format = "json"
# Uses default json template

[profiles.polybar]
format = "text"
text_template = "{artist} - {title} [{quality_info}]"
